import { NODE_DEFS } from "../constants/nodes";

export function generateCode(nodes) {
  if (!nodes.length) return "# Add nodes to generate code";
  const has = (t) => nodes.some((n) => n.type === t);
  const lines = ["# Generated by QdrantFlow\n"];
  if (nodes.some((n) => NODE_DEFS[n.type]?.isQdrant))
    lines.push("from qdrant_client import QdrantClient, models");
  if (has("openai_embed") || has("openai_llm")) lines.push("from openai import OpenAI");
  if (has("cohere_embed") || has("cohere_llm")) lines.push("from cohere import Client as Cohere");
  if (has("anthropic_llm")) lines.push("from anthropic import Anthropic");
  if (has("fastembed")) lines.push("from fastembed import TextEmbedding");
  if (has("reranker")) lines.push("import cohere");
  lines.push("");

  nodes.forEach((n) => {
    const f = n.fields;
    switch (n.type) {
      case "qdrant_collection":
        lines.push(`# Qdrant client — ${f.collection}`);
        lines.push(`client = QdrantClient("${f.host}")`);
        lines.push(`client.recreate_collection(`);
        lines.push(`    collection_name="${f.collection}",`);
        lines.push(`    vectors_config=models.VectorParams(`);
        lines.push(`        size=${f.vector_size}, distance=models.Distance.COSINE`);
        lines.push(`    )`);
        lines.push(`)`);
        break;
      case "qdrant_search":
        lines.push(`# Vector search`);
        lines.push(`results = client.query_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    query=query_vector,`);
        lines.push(`    limit=${f.top_k},`);
        lines.push(`    score_threshold=${f.score_threshold}`);
        lines.push(`)`);
        break;
      case "qdrant_hybrid":
        lines.push(`# Hybrid search — dense + sparse (${f.fusion} fusion)`);
        lines.push(`results = client.query_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    prefetch=[`);
        lines.push(`        models.Prefetch(query=dense_vector, using="dense", limit=${f.top_k}),`);
        lines.push(`        models.Prefetch(query=sparse_vector, using="${f.sparse_model}", limit=${f.top_k}),`);
        lines.push(`    ],`);
        lines.push(`    query=models.FusionQuery(fusion=models.Fusion.${f.fusion}),`);
        lines.push(`    limit=${f.top_k}`);
        lines.push(`)`);
        break;
      case "qdrant_upsert":
        lines.push(`# Batch upsert`);
        lines.push(`client.upload_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    points=[models.PointStruct(id=i, vector=v, payload=p)`);
        lines.push(`            for i, v, p in zip(ids, vectors, payloads)],`);
        lines.push(`    batch_size=${f.batch_size}`);
        lines.push(`)`);
        break;
      case "qdrant_filter":
        lines.push(`# Payload filter`);
        lines.push(`filter_cond = models.Filter(`);
        lines.push(`    ${f.condition}=[models.FieldCondition(key="${f.field}", match=models.MatchValue(value="${f.match}"))]`);
        lines.push(`)`);
        break;
      case "openai_embed":
        lines.push(`# OpenAI embeddings`);
        lines.push(`oai = OpenAI()`);
        lines.push(`resp = oai.embeddings.create(model="${f.model}", input=texts)`);
        lines.push(`vectors = [r.embedding for r in resp.data]`);
        break;
      case "cohere_embed":
        lines.push(`# Cohere embeddings`);
        lines.push(`co = Cohere(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`resp = co.embed(texts=texts, model="${f.model}", input_type="${f.input_type}")`);
        lines.push(`vectors = resp.embeddings`);
        break;
      case "fastembed":
        lines.push(`# FastEmbed (local, no API key)`);
        lines.push(`embedder = TextEmbedding(model_name="${f.model}")`);
        lines.push(`vectors = list(embedder.embed(texts))`);
        break;
      case "anthropic_llm":
        lines.push(`# Claude generation`);
        lines.push(`client_an = Anthropic()`);
        lines.push(`response = client_an.messages.create(`);
        lines.push(`    model="${f.model}",`);
        lines.push(`    max_tokens=${f.max_tokens},`);
        lines.push(`    messages=[{"role": "user", "content": prompt}]`);
        lines.push(`)`);
        lines.push(`answer = response.content[0].text`);
        break;
      case "openai_llm":
        lines.push(`# GPT generation`);
        lines.push(`oai_chat = OpenAI()`);
        lines.push(`response = oai_chat.chat.completions.create(`);
        lines.push(`    model="${f.model}", temperature=${f.temperature},`);
        lines.push(`    messages=[{"role": "user", "content": prompt}]`);
        lines.push(`)`);
        lines.push(`answer = response.choices[0].message.content`);
        break;
      case "cohere_llm":
        lines.push(`# Command R+ generation`);
        lines.push(`co_chat = Cohere(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`response = co_chat.chat(model="${f.model}", message=prompt, documents=documents)`);
        lines.push(`answer = response.text`);
        break;
      case "reranker":
        lines.push(`# Rerank results`);
        lines.push(`co_rerank = cohere.Client(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`reranked = co_rerank.rerank(`);
        lines.push(`    model="${f.model}", query=query, documents=[r.payload["text"] for r in results], top_n=${f.top_n}`);
        lines.push(`)`);
        break;
      case "doc_loader":
        lines.push(`# Load documents from ${f.source}`);
        lines.push(`from pathlib import Path`);
        lines.push(`exts = {".${f.format.split(",").join('", ".')}"}`);
        lines.push(`docs = [p.read_text() for p in Path("${f.source}").rglob("*") if p.suffix in exts]`);
        break;
      case "chunker":
        lines.push(`# Chunk text — size=${f.chunk_size}, overlap=${f.overlap}`);
        lines.push(`def chunk(text, size=${f.chunk_size}, overlap=${f.overlap}):`);
        lines.push(`    step = size - overlap`);
        lines.push(`    return [text[i:i+size] for i in range(0, len(text), step)]`);
        lines.push(`chunks = [c for doc in docs for c in chunk(doc)]`);
        break;
      case "query_input":
        lines.push(`${f.variable} = input("Query: ")`);
        break;
      case "agent_loop":
        lines.push(`# Agentic loop — max ${f.max_iterations} iterations`);
        lines.push(`for step in range(${f.max_iterations}):`);
        lines.push(`    action = llm.decide(memory=qdrant_memory, query=query)`);
        lines.push(`    if action["type"] == "${f.stop_condition}": break`);
        lines.push(`    result = tools.call(action)`);
        break;
      case "tool_caller":
        lines.push(`# Tool dispatch`);
        lines.push(`TOOLS = {t.strip(): globals()[t.strip()] for t in "${f.tools}".split(",")}`);
        lines.push(`result = TOOLS[action["tool"]](**action["args"])`);
        break;
      case "output":
        lines.push(`# Output`);
        lines.push(`print(answer)`);
        break;
      default: break;
    }
    lines.push("");
  });
  return lines.join("\n");
}
