import { NODE_DEFS } from "../constants/nodes";

// ─── PLUGIN CODE-GENERATOR REGISTRY ──────────────────────────────────────────
const _customImports    = {}; // nodeType → import line string
const _customGenerators = {}; // nodeType → (lines: string[], fields: object, node: object) => void

/**
 * Register a Python import line that will be emitted whenever nodes of
 * `nodeType` appear in the graph.
 *
 * @param {string} nodeType   - The node type key, e.g. "my_llm"
 * @param {string} importLine - The Python import statement, e.g. "import requests"
 */
export function registerImport(nodeType, importLine) {
  _customImports[nodeType] = importLine;
}

/**
 * Register a code-generation function for a custom node type.
 * The function receives the shared `lines` array (push to it), the node's
 * `fields` object, and the full `node` object.
 *
 * @param {string}   nodeType    - The node type key, e.g. "my_llm"
 * @param {Function} generatorFn - (lines: string[], fields: object, node: object) => void
 */
export function registerCodeGenerator(nodeType, generatorFn) {
  _customGenerators[nodeType] = generatorFn;
}

export function generateCode(nodes, edges = []) {
  if (!nodes.length) return "# Add nodes to generate code";
  const has = (t) => nodes.some((n) => n.type === t);
  const lines = ["# Generated by QdrantFlow\n"];
  if (nodes.some((n) => NODE_DEFS[n.type]?.isQdrant))
    lines.push("from qdrant_client import QdrantClient, models");
  if (has("openai_embed") || has("openai_llm")) lines.push("from openai import OpenAI");
  if (has("cohere_embed") || has("cohere_llm") || has("reranker")) lines.push("import os");
  if (has("cohere_embed") || has("cohere_llm")) lines.push("from cohere import Client as Cohere");
  if (has("anthropic_llm")) lines.push("from anthropic import Anthropic");
  if (has("fastembed")) lines.push("from fastembed import TextEmbedding");
  if (has("reranker")) lines.push("import cohere");

  // Emit imports registered by plugins
  const seenImports = new Set();
  nodes.forEach((n) => {
    if (_customImports[n.type] && !seenImports.has(n.type)) {
      lines.push(_customImports[n.type]);
      seenImports.add(n.type);
    }
  });

  lines.push("");

  // ── Topological sort so nodes are emitted in data-flow order ──
  const adj = new Map();
  const inDegree = new Map();
  nodes.forEach((n) => { adj.set(n.id, []); inDegree.set(n.id, 0); });
  edges.forEach((e) => {
    if (adj.has(e.from) && adj.has(e.to)) {
      adj.get(e.from).push(e.to);
      inDegree.set(e.to, inDegree.get(e.to) + 1);
    }
  });
  const queue = [];
  inDegree.forEach((deg, id) => { if (deg === 0) queue.push(id); });
  const sortedIds = [];
  while (queue.length) {
    const u = queue.shift();
    sortedIds.push(u);
    adj.get(u).forEach((v) => {
      inDegree.set(v, inDegree.get(v) - 1);
      if (inDegree.get(v) === 0) queue.push(v);
    });
  }
  // Append any nodes in a cycle as fallback
  nodes.forEach((n) => { if (!sortedIds.includes(n.id)) sortedIds.push(n.id); });

  sortedIds.forEach((nodeId) => {
    const n = nodes.find((nd) => nd.id === nodeId);
    if (!n) return;
    const f = n.fields;

    // Delegate to a plugin-registered generator first
    if (_customGenerators[n.type]) {
      _customGenerators[n.type](lines, f, n);
      lines.push("");
      return;
    }

    switch (n.type) {
      case "qdrant_collection":
        lines.push(`# Qdrant client — ${f.collection}`);
        lines.push(`client = QdrantClient("${f.host}")`);
        lines.push(`client.recreate_collection(`);
        lines.push(`    collection_name="${f.collection}",`);
        lines.push(`    vectors_config=models.VectorParams(`);
        lines.push(`        size=${f.vector_size}, distance=models.Distance.COSINE`);
        lines.push(`    )`);
        lines.push(`)`);
        break;
      case "qdrant_search":
        lines.push(`# Vector search`);
        lines.push(`collection_name = "${f.collection || "collection_name"}"`);
        lines.push(`results = client.query_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    query=vectors[0] if 'vectors' in locals() else [],`);
        lines.push(`    limit=${f.top_k},`);
        lines.push(`    score_threshold=${f.score_threshold}`);
        lines.push(`)`);
        break;
      case "qdrant_hybrid":
        lines.push(`# Hybrid search — dense + sparse (${f.fusion} fusion)`);
        lines.push(`collection_name = "${f.collection || "collection_name"}"`);
        lines.push(`results = client.query_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    prefetch=[`);
        lines.push(`        models.Prefetch(query=vectors[0] if 'vectors' in locals() else [], using="dense", limit=${f.top_k}),`);
        lines.push(`        models.Prefetch(query=sparse_vectors[0] if 'sparse_vectors' in locals() else [], using="${f.sparse_model}", limit=${f.top_k}),`);
        lines.push(`    ],`);
        lines.push(`    query=models.FusionQuery(fusion=models.Fusion.${f.fusion}),`);
        lines.push(`    limit=${f.top_k}`);
        lines.push(`)`);
        break;
      case "qdrant_upsert":
        lines.push(`# Batch upsert`);
        lines.push(`collection_name = "${f.collection || "collection_name"}"`);
        lines.push(`client.upload_points(`);
        lines.push(`    collection_name=collection_name,`);
        lines.push(`    points=[models.PointStruct(id=i, vector=v, payload=p)`);
        lines.push(`            for i, (v, p) in enumerate(zip(vectors if 'vectors' in locals() else [], payloads if 'payloads' in locals() else []))],`);
        lines.push(`    batch_size=${f.batch_size}`);
        lines.push(`)`);
        break;
      case "qdrant_filter":
        lines.push(`# Payload filter`);
        lines.push(`filter_cond = models.Filter(`);
        lines.push(`    ${f.condition}=[models.FieldCondition(key="${f.field}", match=models.MatchValue(value="${f.match}"))]`);
        lines.push(`)`);
        break;
      case "openai_embed":
        lines.push(`# OpenAI embeddings`);
        lines.push(`oai = OpenAI()`);
        lines.push(`resp = oai.embeddings.create(model="${f.model}", input=texts)`);
        lines.push(`vectors = [r.embedding for r in resp.data]`);
        break;
      case "cohere_embed":
        lines.push(`# Cohere embeddings`);
        lines.push(`co = Cohere(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`resp = co.embed(texts=texts, model="${f.model}", input_type="${f.input_type}")`);
        lines.push(`vectors = resp.embeddings`);
        break;
      case "fastembed":
        lines.push(`# FastEmbed (local, no API key)`);
        lines.push(`embedder = TextEmbedding(model_name="${f.model}")`);
        lines.push(`vectors = list(embedder.embed(texts))`);
        break;
      case "anthropic_llm":
        lines.push(`# Claude generation`);
        lines.push(`client_an = Anthropic()`);
        lines.push(`response = client_an.messages.create(`);
        lines.push(`    model="${f.model}",`);
        lines.push(`    max_tokens=${f.max_tokens},`);
        lines.push(`    messages=[{"role": "user", "content": prompt}]`);
        lines.push(`)`);
        lines.push(`answer = response.content[0].text`);
        break;
      case "openai_llm":
        lines.push(`# GPT generation`);
        lines.push(`oai_chat = OpenAI()`);
        lines.push(`response = oai_chat.chat.completions.create(`);
        lines.push(`    model="${f.model}", temperature=${f.temperature},`);
        lines.push(`    messages=[{"role": "user", "content": prompt}]`);
        lines.push(`)`);
        lines.push(`answer = response.choices[0].message.content`);
        break;
      case "cohere_llm":
        lines.push(`# Command R+ generation`);
        lines.push(`co_chat = Cohere(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`response = co_chat.chat(model="${f.model}", message=prompt, documents=documents)`);
        lines.push(`answer = response.text`);
        break;
      case "reranker":
        lines.push(`# Rerank results`);
        lines.push(`co_rerank = cohere.Client(api_key=os.environ["COHERE_API_KEY"])`);
        lines.push(`reranked = co_rerank.rerank(`);
        lines.push(`    model="${f.model}", query=query, documents=[r.payload["text"] for r in results], top_n=${f.top_n}`);
        lines.push(`)`);
        break;
      case "doc_loader":
        lines.push(`# Load documents from ${f.source}`);
        lines.push(`from pathlib import Path`);
        lines.push(`exts = {".${f.format.split(",").map((s) => s.trim()).join('", ".')}"}`);
        lines.push(`docs = [p.read_text() for p in Path("${f.source}").rglob("*") if p.suffix in exts]`);
        break;
      case "chunker":
        lines.push(`# Chunk text — size=${f.chunk_size}, overlap=${f.overlap}`);
        lines.push(`def chunk(text, size=${f.chunk_size}, overlap=${f.overlap}):`);
        lines.push(`    step = size - overlap`);
        lines.push(`    return [text[i:i+size] for i in range(0, len(text), step)]`);
        lines.push(`chunks = [c for doc in docs for c in chunk(doc)]`);
        break;
      case "query_input":
        lines.push(`${f.variable} = input("Query: ")`);
        break;
      case "agent_loop":
        lines.push(`# Agentic loop — max ${f.max_iterations} iterations`);
        lines.push(`for step in range(${f.max_iterations}):`);
        lines.push(`    action = llm.decide(memory=qdrant_memory, query=query)`);
        lines.push(`    if action["type"] == "${f.stop_condition}": break`);
        lines.push(`    result = tools.call(action)`);
        break;
      case "tool_caller":
        lines.push(`# Tool dispatch`);
        lines.push(`TOOLS = {t.strip(): globals()[t.strip()] for t in "${f.tools}".split(",")}`);
        lines.push(`result = TOOLS[action["tool"]](**action["args"])`);
        break;
      case "output":
        lines.push(`# Output`);
        lines.push(`print(answer)`);
        break;
      default: break;
    }
    lines.push("");
  });
  return lines.join("\n");
}
